adding docker build and end to end testing in .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,7 +3,8 @@
 # jobs defined for them qualify based on the event (merge, commit, parse commit message)
 
 stages:
-  - test
+  - unit-int-test
+  - build-e2e
    
 
 ### ------------------------------------ END OF STAGES ---------------------------------------- ###
@@ -69,7 +70,7 @@ stages:
 
 # test job for python 3.9 running on linux
 test-linux-py39:                                                      # name of the job
-  stage: test                                                         # the stage the job belongs to
+  stage: unit-int-test                                                         # the stage the job belongs to
   image: python:3.9.8-slim-bullseye                                   # use this docker image to run the job
   tags:
     - shared-linux                                                    # use runner with this tag
@@ -100,7 +101,7 @@ test-linux-py39:                                                      # name of 
 
 # test job for python 3.10 running on linux
 test-linux-py310:                                                     # name of the job
-  stage: test                                                         # the stage the job belongs to
+  stage: unit-int-test                                                         # the stage the job belongs to
   image: python:3.10.1-slim-bullseye                                  # use this docker image to run the job
   tags:
     - shared-linux                                                    # use runner with this tag
@@ -131,7 +132,7 @@ test-linux-py310:                                                     # name of 
 
 # test job for python 3.10 windows
 test-win-py310:                                                       # name of the job
-  stage: test                                                         # the stage the job belongs to
+  stage: unit-int-test                                                         # the stage the job belongs to
   image: python:3.10-windowsservercore-1809                           # the docker image to use for running the job
   tags:
     - shared-win                                                      # use runner with this tag
@@ -159,3 +160,69 @@ test-win-py310:                                                       # name of 
 # --------------------- jobs ----------------------- #
 
 ### ----------------------------------------- END OF TEST JOBS ----------------------------------------- ###
+
+
+
+# create reusable script for building docker image and testing 
+.script-build-e2e: &script-build-e2e
+  - apk update                                                                                                              # update repository
+  - apk upgrade                                                                                                             # upgrade the system
+  - apk add --no-cache python3 py3-pip                                                                                      # install python
+  - apk add docker-compose                                                                                                  # install docker-compose
+  - pip install .
+  - export DOCKER_BUILDKIT=1                                                                                                # set docker buildkit env var
+  - docker build -t traffic-man:build .                                                                                # attempt to build the docker image we will test
+  - mkdir -p /builds/mnt/traffic-man-etc                                                                                                   
+  - mkdir -p /etc/traffic-man
+  - cd tests/End2End
+  - docker build -t twiliotest-api:latest -f DockerfileTwilioTestAPI                                                                                                                # move into the tests directory
+  - docker-compose up -d                                                                                                    # stand up our test environment/docker containers described by the docker-compose.yml file in the tests dir
+  - sleep 3                                                                                                                 # give the containers a few seconds to start
+  - docker ps -a                                                                                                            # take a look at the environment we just stood up
+  - ls -lh /builds/mnt/traffic-man-etc
+  - export $(grep -v '^#' .env | xargs)
+  - python3 test_script.py
+  - test_api_error=$(cat /builds/mnt/etc-testapi/testapi.log | { grep -c "\[ERROR\]" || true; })                                                          
+  - |                                                                                                                       # check every 100 seconds to see if the uploads are done; stop looping if any errors are found - note:expecting 2 completed uploads based on app config and size of test upload file
+      echo "---- checking log ----";
+      test_api_error=$(cat /builds/mnt/traffic-man-etc/traffic-man.log | { grep -c "\[ERROR\]" || true; });
+
+      if [[ "$test_api_error" == 0 ]]; 
+        then echo "no errors found in logs";
+        else echo "errors found in logs" && 
+            echo " ------ traffic-man.log ---------" &&
+            cat /builds/mnt/traffic-man-etc/traffic-man.log && 
+            exit 1;
+      fi;
+  - cat /builds/mnt/traffic-man-etc/traffic-man.log                                                              # print the onedrive-offsite.log file
+
+# build job to build docker image and verify it is working
+build-test:
+  stage: build-e2e
+  image: docker:23.0.1-alpine3.17                          # need alpine so we can install and use curl for testing
+  tags:
+    - shared-docker
+  variables:
+    DOCKER_TLS_CERTDIR: "/certs"
+
+  services:
+    - docker:23-dind                                             # this is a second container providing the docker daemon, it can be accessed with just the name 'docker'
+  before_script:
+    - docker info
+
+  script: *script-build-e2e
+
+  rules:
+    - if: $CI_COMMIT_BRANCH == "user-registration"                    # Execute this job if the commit target branch is dev. This includes pushes from users and post merge commits
+      changes: *changes                                               # Execute the job if any of the files we care about were changed as defined above.
+      when: on_success                                                # Execute job if jobs from previous stage are successful.
+
+    - if: $CI_COMMIT_BRANCH == "dev"                                  # Execute this job if the commit target branch is dev. This includes pushes from users and post merge commits
+      changes: *changes                                               # Execute the job if any of the files we care about were changed as defined above.
+      when: on_success                                                # Execute job if jobs from previous stage are successful.
+
+    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"               # Execute this job if the merge target branch is dev
+      changes: *changes                                               # Execute the job if any of the files we care about were changed as defined above.
+      when: on_success   
+
+    - when: never                                                     # If no criteria were matched, do not run this job
